/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-05-30 14:26:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/Users/sixt/git/recruit/README.md/apache-tomcat-9.0.56/wtpwebapps/recruit_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1645234482345L));
    _jspx_dependants.put("jar:file:/Users/sixt/git/recruit/README.md/apache-tomcat-9.0.56/wtpwebapps/recruit_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/x.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/sixt/git/recruit/README.md/apache-tomcat-9.0.56/wtpwebapps/recruit_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/sixt/git/recruit/README.md/apache-tomcat-9.0.56/wtpwebapps/recruit_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/Users/sixt/git/recruit/README.md/apache-tomcat-9.0.56/wtpwebapps/recruit_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("  \n");
      out.write(" \n");
      out.write("   \n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/b4e02812b5.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<title>recruit</title>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("td {\n");
      out.write("	font-size: 14px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("textarea {\n");
      out.write("	font-size: 14px;\n");
      out.write("	resize: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("var now = [];\n");
      out.write("\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<section class=\"container border\">\n");
      out.write("\n");
      out.write("	<p class=\"mt-2 font-italic display-4 text-center\">Recruit</p>\n");
      out.write("	\n");
      out.write("	<hr />\n");
      out.write("	\n");
      out.write("	<a href=\"https://calendar.google.com/calendar/u/0/r/month/2022/5/1?tab=rc&pli=1\" target=\"_blink\" class=\"btn btn-sm btn-primary mb-2 float-right ml-1\">상세일정</a>\n");
      out.write("	<a href=\"reg\" class=\"btn btn-sm btn-dark mb-2 float-right\">등록</a>\n");
      out.write("	\n");
      out.write("	<span class=\"mx-3\"></span>\n");
      out.write("	\n");
      out.write("	<button id=\"show_all\" class=\"btn btn-sm btn-default font-italic\">전체보기</button>\n");
      out.write("	<button id=\"show_paper\" class=\"btn btn-sm btn-default font-italic\">서류 대기중</button>\n");
      out.write("	<button id=\"show_test\" class=\"btn btn-sm btn-default font-italic\">코딩테스트</button>\n");
      out.write("	<button id=\"show_1st\" class=\"btn btn-sm btn-default font-italic\">1차 대기중</button>\n");
      out.write("	<button id=\"show_2nd\" class=\"btn btn-sm btn-default font-italic\">2차 대기중</button>\n");
      out.write("	<button id=\"show_over\" class=\"btn btn-sm btn-default font-italic\">불합격</button>\n");
      out.write("	<button id=\"toggle_over\" class=\"btn btn-sm btn-default font-italic\">불합격 제외하기</button>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<table id=\"table\" class=\"table table-hover text-center\">\n");
      out.write("		<thead>\n");
      out.write("			<tr class=\"row mx-0\">\n");
      out.write("				<th class=\"col-4\">회사명</th>\n");
      out.write("				<th class=\"col-2\">지원일</th>\n");
      out.write("				<th class=\"col-2\">마감일</th>\n");
      out.write("				<th class=\"col-2\">현황</th>\n");
      out.write("				<th class=\"col-1\">링크</th>\n");
      out.write("				<th class=\"col-1\">위치</th>\n");
      out.write("			</tr>\n");
      out.write("		</thead>\n");
      out.write("		\n");
      out.write("		<tbody>\n");
      out.write("			");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("		</tbody>\n");
      out.write("	</table>\n");
      out.write("\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("let overCount = 0;\n");
      out.write("let count = now.length;\n");
      out.write("\n");
      out.write("$(document).ready(function() {\n");
      out.write("	\n");
      out.write("	$('span').text('총 ' + count + '건');\n");
      out.write("	\n");
      out.write("	$('.btn-default').click(function() {\n");
      out.write("		\n");
      out.write("		var id = $(this).attr('id');\n");
      out.write("		var txt = $(this).text();\n");
      out.write("		\n");
      out.write("		$('tr.infosub').addClass('d-none');\n");
      out.write("		\n");
      out.write("		if ( id == 'toggle_over' ) {\n");
      out.write("			\n");
      out.write("			var count_over = 0;\n");
      out.write("			overCount++;\n");
      out.write("			\n");
      out.write("			if ( overCount%2 != 0 ) {\n");
      out.write("				$(this).addClass('btn-info');\n");
      out.write("			} else {\n");
      out.write("				$(this).removeClass('btn-info');\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			for ( var i = 0; i < now.length; i++ ) {\n");
      out.write("				\n");
      out.write("				var obj = now[i];\n");
      out.write("				\n");
      out.write("				console.log(obj.id);\n");
      out.write("				\n");
      out.write("				if ( obj.now == '불합격' && overCount%2 != 0 ) {\n");
      out.write("					\n");
      out.write("					$(\"tr#infobox\"+obj.id).addClass('d-none');\n");
      out.write("					count_over++;\n");
      out.write("					\n");
      out.write("				} \n");
      out.write("				\n");
      out.write("				else if ( obj.now == '불합격' && overCount%2 == 0 ){\n");
      out.write("					\n");
      out.write("					$(\"tr#infobox\"+obj.id).removeClass('d-none');\n");
      out.write("					\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			if ( count_over > 0 ) {\n");
      out.write("				$('span').text('총 ' + (count-count_over) + '건');\n");
      out.write("			} \n");
      out.write("	\n");
      out.write("			else {\n");
      out.write("				$('span').text('총 ' + count + '건');\n");
      out.write("			}\n");
      out.write("\n");
      out.write("		} \n");
      out.write("		\n");
      out.write("		else if ( id == 'show_all' ) {\n");
      out.write("			count = now.length;\n");
      out.write("			$('tr.infomain').removeClass('d-none');\n");
      out.write("			$('span').text('총 ' + count + '건');\n");
      out.write("			$('button#toggle_over').removeClass('d-none');\n");
      out.write("			\n");
      out.write("			$('.btn-default').removeClass('btn-info');\n");
      out.write("			$('.btn-default').removeClass('btn-dark');\n");
      out.write("			$(this).addClass('btn-dark');\n");
      out.write("			\n");
      out.write("			if ( overCount%2 != 0 ) {\n");
      out.write("				overCount++;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		else {\n");
      out.write("			$('.btn-default').removeClass('btn-info');\n");
      out.write("			$('.btn-default').removeClass('btn-dark');\n");
      out.write("			$(this).addClass('btn-dark');\n");
      out.write("			\n");
      out.write("			showWhat(txt, now);\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$('tr.infomain').click(function() {\n");
      out.write("\n");
      out.write("		var id = $(this).attr('id');\n");
      out.write("		var count = $(this).attr('data-count');\n");
      out.write("		\n");
      out.write("		if ( count%2 != 0 ) {\n");
      out.write("			$('tr.infomain').attr('data-count', 1);		\n");
      out.write("			$('tr.infomain').removeClass('bg-light');\n");
      out.write("			$(this).addClass('bg-light');			\n");
      out.write("			\n");
      out.write("			$(this).attr('data-count', 2);\n");
      out.write("			$('tr.infosub').addClass('d-none');\n");
      out.write("			$('tr.infosub.' + id).removeClass('d-none');\n");
      out.write("			\n");
      out.write("		} else {\n");
      out.write("			$('tr.infomain').attr('data-count', 1);\n");
      out.write("			$('tr.infomain').removeClass('bg-light');\n");
      out.write("			$('tr.infosub.' + id).addClass('d-none');\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("	})\n");
      out.write("});\n");
      out.write("\n");
      out.write("function showWhat(txt, arr) {\n");
      out.write("	\n");
      out.write("	var show_count = 0;\n");
      out.write("	\n");
      out.write("	for ( var i = 0; i < arr.length; i++ ) {\n");
      out.write("		\n");
      out.write("		var obj = arr[i];\n");
      out.write("\n");
      out.write("		if ( obj.now == txt ) {\n");
      out.write("			\n");
      out.write("			$(\"tr#infobox\"+obj.id).removeClass('d-none');\n");
      out.write("			show_count++;\n");
      out.write("		} \n");
      out.write("		\n");
      out.write("		else {\n");
      out.write("			\n");
      out.write("			$(\"tr#infobox\"+obj.id).addClass('d-none');\n");
      out.write("			\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	count = show_count;\n");
      out.write("	\n");
      out.write("	$('span').text('총 ' + show_count + '건');\n");
      out.write("	$('button#toggle_over').addClass('d-none');\n");
      out.write("	\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(37,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(37,0) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/home.jsp(37,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	\n");
            out.write("	var obj = {\n");
            out.write("			id : '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.idnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("',\n");
            out.write("			now : '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.rCurrent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("',\n");
            out.write("			endDate : '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.endDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("',\n");
            out.write("			rDate : '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.rdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("'\n");
            out.write("	};\n");
            out.write("		\n");
            out.write("	now.push(obj);\n");
            out.write("	\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(90,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(90,3) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/home.jsp(90,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("dto");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("				<tr id=\"infobox");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.idnum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"row mx-0 infobox");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.idnum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" infomain\" data-count=1 style=\"cursor: pointer;\">\n");
            out.write("					<td id=\"name\" class=\"name col-4\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("					<td id=\"date\" class=\"date col-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.rdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("					<td id=\"end_date\" class=\"end_date col-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.endDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("					<td id=\"now");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.idnum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"now col-2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.rCurrent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("\n");
            out.write("					<td id=\"location\" class=\"location col-1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.rLocation}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("					\n");
            out.write("					<td class=\"link col-1\">\n");
            out.write("						<a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.rLink}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" target=\"_blink\">\n");
            out.write("							<i class=\"fa-solid fa-arrow-up-right-from-square\"></i>\n");
            out.write("						</a>\n");
            out.write("					</td>\n");
            out.write("					\n");
            out.write("				</tr>\n");
            out.write("				\n");
            out.write("				<tr class=\"row mx-0 infobox");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.idnum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" infosub d-none bg-light py-2\">\n");
            out.write("					<td class=\"col-2 border-bottom font-italic ml-5 mr-2 mb-2\"><b>포지션</b></td>\n");
            out.write("					<td class=\"col-7 border-bottom font-italic mr-2 mb-2\"><b>진행상황</b></td>\n");
            out.write("					<td class=\"col-2 border-bottom font-italic mb-2\"><b>예상연봉</b></td>\n");
            out.write("					<td class=\"col-2 border rounded ml-5 mr-2\" style=\"border-top: none;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.rPosition}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("					<td class=\"col-7 border rounded mr-2 text-left\" style=\"border-top: none;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.rDesc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("					<td class=\"col-2 border rounded\" style=\"border-top: none;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.pay }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("만원</td>\n");
            out.write("					\n");
            out.write("					");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\n");
            out.write("					\n");
            out.write("					<td class=\"col-12 row mx-0 justify-content-center\" style=\"border-top: none;\">\n");
            out.write("						<a href=\"mod?idnum=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.idnum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"col-5 btn btn-sm btn-primary border-white\">수정</a>\n");
            out.write("						<a href=\"del?idnum=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.idnum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"col-5 btn btn-sm btn-danger border-white\">삭제</a>\n");
            out.write("					</td>\n");
            out.write("				</tr>\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/home.jsp(115,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.review != ''}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<td class=\"col-11 ml-5\" style=\"border-top: none;\">\n");
          out.write("							<textarea class=\"form-control\" rows=\"10\" readonly>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.review}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</textarea>\n");
          out.write("						</td>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
